### ISSUE TITLE
Supply teleporter stuck

### ISSUE THREAD

**Issue by artbelikov** [EnemyArea/ONI-Mods#1]
Hi. I have a problem. After supplying crude oil to the Supply teleporter over solids rail the teleporter stuck and does not transfer any more items, even after disabling this mod. Gasses and liquids are still able to transfer.|
Can you help me? Maybe it has some internal container that has to be reseted?

**Comment by artbelikov** [comment]
Resolved by rebuilding the teleporter in debug mode.

**Comment by soerenkk** [comment]
I have the exact same issue, please fix this.

For now until a fix is provided, how can you rebuild in the debug mode, will it affect the save and how about acheivements?
