### ISSUE TITLE
Supply teleporter stuck #2

### ISSUE THREAD

**Issue by soerenkk** [EnemyArea/ONI-Mods#3]
Having the same issue as descripted in issue #1

Reporter on #1 mentioned a solution that worked for him was to replace the maskine in debug mode. I asked a few questions in #1, but no response at all yet, hence why I'm opening a new issue ticket.

**Comment by EnemyArea** [comment]
Hey there! Yes there are many bugs in that mods. Sadly I'm currently have not the time to fix them. The updates from klei always messing up these mods....

**Comment by soerenkk** [comment]
Could you perhaps make a quick thing that could empty the thing so i could not do that again or even disable the mod until a more permanent solution have been implementet?

Maybe something simple as an "empty pipe" command or something just to make the device work again. Maybe even just drop it on the ground where the input device is.

**Comment by EnemyArea** [comment]
Sorry but I removed the mod due to the updates that broke quite a few mods.
